dubbo:
  application:
    name: dubbo-customer-web
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: XXXX
  consumer:
    timeout: 5000

server:
  port: 8080

spring:
  application:
    name: burgundred-web
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**

redis:
  host: XXXX
